// ignore_for_file: unused_import

// file automatically generated by running:
// dart run coverage_helper.dart

import 'package:monster_finances/providers/account_query_provider.dart';
import 'package:monster_finances/providers/total_amount_by_account_provider.dart';
import 'package:monster_finances/providers/database_provider.dart';
import 'package:monster_finances/providers/total_amount_by_account_type_provider.dart';
import 'package:monster_finances/providers/account_list_provider.dart';
import 'package:monster_finances/providers/current_account_provider.dart';
import 'package:monster_finances/providers/total_amount_provider.dart';
import 'package:monster_finances/queries/accounts.dart';
import 'package:monster_finances/utils/screen_util.dart';
import 'package:monster_finances/utils/text_util.dart';
import 'package:monster_finances/utils/select_account_util.dart';
import 'package:monster_finances/utils/initial_data/dev_data/account_data.dart';
import 'package:monster_finances/utils/initial_data/dev_data/transaction_data.dart';
import 'package:monster_finances/utils/initial_data/dev_data/account_responsible_data.dart';
import 'package:monster_finances/utils/initial_data/category_data.dart';
import 'package:monster_finances/utils/initial_data/account_type_data.dart';
import 'package:monster_finances/utils/initial_data/initial_data.dart';
import 'package:monster_finances/main.dart';
import 'package:monster_finances/config.dart';
import 'package:monster_finances/views/account_info_page/account_info_page.dart';
import 'package:monster_finances/views/account_transactions_page/account_transactions_page.dart';
import 'package:monster_finances/views/not_found.dart';
import 'package:monster_finances/views/splash_page.dart';
import 'package:monster_finances/views/overview_page/overview_page.dart';
import 'package:monster_finances/views/overview_page/accounts_page.dart';
import 'package:monster_finances/views/overview_page/empty_page.dart';
import 'package:monster_finances/views/transaction_page/transaction_page.dart';
import 'package:monster_finances/widgets/list_chip.dart';
import 'package:monster_finances/widgets/error_indicator.dart';
import 'package:monster_finances/widgets/progress_indicator.dart';
import 'package:monster_finances/widgets/list_input.dart';
import 'package:monster_finances/entities/account_responsible.dart';
import 'package:monster_finances/entities/account_type.dart';
import 'package:monster_finances/entities/account.dart';
import 'package:monster_finances/entities/tag.dart';
import 'package:monster_finances/entities/category.dart';
import 'package:monster_finances/entities/transaction.dart';
import 'package:monster_finances/store/store.dart';

void main() {}
